export const APP_ROUTES = {
	dashboard: '/dashboard',
	faqs: '/faqs',
	friends: '/friends',
	gaming: {
		initial: '/gaming/',
		games: '/gaming/games',
		myMatches: '/gaming/my-matches',
		myTournaments: '/gaming/my-tournaments',
		myChallenges: '/gaming/my-challenges',
	},
	leaderboard: {
		initial: '/leaderboard/',
		valorant: '/leaderboard/valorant',
		cod: '/leaderboard/cod',
		pubg: '/leaderboard/pubg',
		apexLegend: '/leaderboard/apex-legend',
		destiny2: '/leaderboard/destiny2',
		leagueOfLegend: '/leaderboard/league-of-legend',
		fortnite: '/leaderboard/fortnite',
		counterStrike: '/leaderboard/counter-strike',
		overwatch: '/leaderboard/overwatch',
	},
	home: '/',
	login: '/login',
	matches: {
		initial: '/match',
		view: `/match/:id/`,
		use_view: (id: string) => `/match/${id}/`,
		overview: `/match/:id/overview`,
		use_overview: (id: string) => `/match/${id}/overview`,
		summary: `/match/:id/summary`,
		use_summary: (id: string) => `/match/${id}/summary`,
	},
	playground: '/playground',
	playerProfile: {
		initial: '/player-profile/',
		overview: '/player-profile/overview',
		agents: '/player-profile/agents',
		weapons: '/player-profile/weapons',
		maps: '/player-profile/maps',
	},
	profile: '/profile',
	register: '/register',
	settings: '/settings',

	teams: '/teams',
	tournaments: {
		initial: '/tournament',
		view: `/tournament/:id/`,
		use_view: (id: string) => `/tournament/${id}/`,
		overview: `/tournament/:id/overview`,
		use_overview: (id: string) => `/tournament/${id}/overview`,
		matches: `/tournament/:id/matches`,
		use_matches: (id: string) => `/tournament/${id}/matches`,
		match: `/tournament/:id/matches/:matchId`,
		use_match: (id: string, matchId: string) => `/tournament/${id}/matches/${matchId}`,
		bracket: `/tournament/:id/bracket`,
		use_bracket: (id: string) => `/tournament/${id}/bracket`,
		teams: `/tournament/:id/teams`,
		use_teams: (id: string) => `/tournament/${id}/teams`,
		results: `/tournament/:id/results`,
		use_results: (id: string) => `/tournament/${id}/results`,
	},
	wallet: '/wallet',
};
