export const APP_ROUTES = {
	dashboard: '/dashboard',
	faqs: '/faqs',
	friends: '/friends',
	gaming: '/gaming',
	leaderboard: '/leaderboard',
	home: '/',
	login: '/login',
	playground: '/playground',
	profile: '/profile',
	register: '/register',
	settings: '/settings',
	stream: '/stream',
	teams: '/teams',
	tournaments: '/tournaments',
	wallet: '/wallet',
};
