export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as PageNotFound } from './404';
export { default as Playground } from './Playground';
export { default as SignIn } from './Auth/SignIn';
export { default as SignUp } from './Auth/SignUp';

// Pages on dashboard layout
export { default as Dashboard } from './Dashboard';
export { default as Gaming } from './Gaming/Layout';
export { default as GamingGames } from './Gaming/Games';
export { default as GamingMatches } from './Gaming/Matches';
export { default as GamingTournaments } from './Gaming/Tournaments';
export { default as GamingChallenges } from './Gaming/Challenges';
export { default as Leaderboard } from './Leaderboard/Layout';
export { default as LeaderboardValorant } from './Leaderboard/Valorant';
export { default as LeaderboardProfile } from './Leaderboard/Profile/Layout';
export { default as LeaderboardProfileAgents } from './Leaderboard/Profile/Agents';
export { default as LeaderboardProfileWeapons } from './Leaderboard/Profile/Weapons';
export { default as LeaderboardProfileMaps } from './Leaderboard/Profile/Maps';
export { default as LeaderboardProfileOverview } from './Leaderboard/Profile/Overview';
export { default as Tournaments } from './Tournaments';
export { default as Teams } from './Teams';
export { default as Friends } from './Friends';
export { default as Stream } from './Stream';
export { default as Wallet } from './Wallet';
export { default as Profile } from './Profile';
export { default as Settings } from './Settings';
export { default as Faqs } from './Faqs';
